<a href="https://colab.research.google.com/github/freefunction/Python_datascience/blob/master/03_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create a list of covid19 cases 

covid_cases = [200,250,350,450,600,900,1300]

In [ ]:
#import numpy package as np

import numpy as np

In [ ]:
#create and print out a numpy array from covid list

np_covid_cases = np.array(covid_cases)
print(np_covid_cases)

[ 200  250  350  450  600  900 1300]


In [ ]:
#print out the type of np_covid_cases

print(type(np_covid_cases))

<class 'numpy.ndarray'>


In [ ]:
#convert the covid19 cases to cases per population 

print(np_covid_cases /100_000)

[0.002  0.0025 0.0035 0.0045 0.006  0.009  0.013 ]


In [ ]:
#convert the covid cases to cases per population using the list 

list_cases_per_pop =[]
for x in covid_cases:
  list_cases_per_pop.append(x/100_000)
print(list_cases_per_pop)

[0.002, 0.0025, 0.0035, 0.0045, 0.006, 0.009, 0.013]


In [ ]:
#print out the first 4 days : index from 0 to 4 excluded 

print(np_covid_cases[0:4])

[200 250 350 450]


In [ ]:
#print out the first 4 days with step of 2

print(np_covid_cases[0:4:2])

[200 350]


In [ ]:
#print out if the cases exceed 250

print(np_covid_cases > 250)

[False False  True  True  True  True  True]


In [ ]:
#print out the values that exceed 250

print(np_covid_cases[np_covid_cases > 250])

[ 350  450  600  900 1300]


In [ ]:
#create covid list of lists 

covid= [[200,2],[250,3],[350,3],[450,4],[600,5],[900,7],[1300,11]]

In [ ]:
#create and print out 2D numpy array

np_covid = np.array(covid)
print(covid)
print(np_covid)

[[200, 2], [250, 3], [350, 3], [450, 4], [600, 5], [900, 7], [1300, 11]]
[[ 200    2]
 [ 250    3]
 [ 350    3]
 [ 450    4]
 [ 600    5]
 [ 900    7]
 [1300   11]]


In [ ]:
#print out the dimension and shape of np_covid

print(np_covid.ndim)
print(np_covid.shape)

2
(7, 2)


In [ ]:
#print out the covid cases and death of the first 4 days 

print(np_covid[0:4,:])

[[200   2]
 [250   3]
 [350   3]
 [450   4]]


In [ ]:
#print out only the covid cases of the 2 last days 

print(np_covid[-2:,0])

[ 900 1300]


In [ ]:
#print out the covid cases +100 and the covid deaths +10 using the broadcasting 

print(np_covid + np.array([100,10]))

[[ 300   12]
 [ 350   13]
 [ 450   13]
 [ 550   14]
 [ 700   15]
 [1000   17]
 [1400   21]]


In [ ]:
#calculate the mean or the average 

print("average of covid cases: "+ str(np_covid[:,0].mean()))
print("average of covid deaths: "+ str(np_covid[:,1].mean()))

average of covid cases: 578.5714285714286
average of covid deaths: 5.0


In [ ]:
#calculate the standard deviation 

print("std of covid cases: "+ str(np_covid[:,0].std()))
print("std of covid deaths: "+ str(np_covid[:,1].std()))

std of covid cases: 367.2845752052126
std of covid deaths: 2.878491668515698


In [ ]:
#calculate the correlation between the covid cases and covid deaths

print("correlation: \n" + str(np.corrcoef(np_covid[:,0], np_covid[:,1])))

correlation: 
[[1.         0.99316552]
 [0.99316552 1.        ]]
